on: push
name: Troyweb
jobs:
  artifactoryUpload:
    name: Upload Troyweb
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1.2.0
  
      with:
        
         #url:  'https://daniainavilli.jfrog.io/artifactory/local_10_19/'
          url:  'https://daniainavilli.jfrog.io/artifactory/local10_20/'
          credentials type: 'accesstoken'
          accesstoken: ${{ secrets.local_10_19 }}
          args: u "dist/*"D:\a\Troyweb\Troyweb\Troyweb" --recursive=true --build-name=Troyweb
