on: push
name: Troyweb
jobs:
  artifactoryUpload:
    name: Upload Troyweb
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1.2.0
  
      with:
        #url: 'https://daniainavilli.jfrog.io/ui/repos/tree/General/local'
         url:  'https://daniainavilli.jfrog.io/ui/admin/repositories/local/local_10_19'  
         credentials type: 'accesstoken'
         accesstoken: ${{ secrets.RT_ACCESSTOKEN }}
         args: u "dist/*"C:\Troyweb-main\Troyweb\bin\Debug" --recursive=true --build-name=Troyweb
