on: push
name: Troyweb
jobs:
  artifactoryUpload:
    name: Upload Troyweb
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1.2.0
  
      with:
          url: 'https://daniainavilli.jfrog.io/ui/repos/tree/General/local' 
          credentials type: '"${{ secrets.JFROG_USER_NAME }}" , $JfrogPassword'
          accesstoken: ${{ secrets.RT_ACCESSTOKEN }}
           path:"D:\a\Troyweb\Troyweb\Troyweb"
 
